# Generated by Django 4.0.6 on 2022-07-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0002_rename_userprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_media_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
