name: Pylint

on: push

jobs:
  test-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: dockerfile_tests:latest

      - name: Start container
        run: docker run --name test-container dockerfile_tests:latest

      - name: Run tests
        run: docker exec test-container python -m manage.py test

      - name: Check test results
        run: |
          test_exit_code=$(docker inspect --format='{{.State.ExitCode}}' test-container)
          if [ $test_exit_code -eq 0 ]; then
            echo "Tests passed successfully!"
          else
            echo "Tests failed with exit code $test_exit_code"
            exit 1
          fi
