name: Django_tests

on: push

jobs:
  test-container:
    runs-on: ubuntu-latest
    env:
      HOST : ${{ secrets.HOST }}
      NAME : ${{ secrets.NAME }}
      USER : ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      PORT: ${{ secrets.PORT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose up -d --build
        
      - name: Wait for container to start
        run: sleep 240

      - name: Run tests
        run: docker-compose exec web python -m manage.py test

      - name: Check test results
        run: |
          test_exit_code=$(docker inspect --format='{{.State.ExitCode}}' dockerfile_tests_web_1)
          if [ $test_exit_code -eq 0 ]; then
            echo "Tests passed successfully!"
          else
            echo "Tests failed with exit code $test_exit_code"
            exit 1
