name: Pylint

on: push

jobs:
  lint:
    name: Run pylint on selected file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy selected file to temporary directory
        run: cp ./templates/home.html /tmp/selected_file

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Pylint
        run: pip install pylint

      - name: Run pylint
        run: pylint /tmp/selected_file
