name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy selected file to temporary directory
        run: cp ./members/views.py /tmp/selected_file

      - name: Run Super-Linter on selected file
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_WORKSPACE: /tmp/super-linter
          RUN_LOCAL: true
        with:
          entrypoint: /usr/bin/super-linter
          args: --file /tmp/selected_file --no-colors --json --output /tmp/lint-results.json --reporter github-pr-review
